// import 'bootstrap/dist/css/bootstrap.min.css'
import '../styles/globals.css'
import '../styles/scss/global.scss'
import Image from 'next/image'
import Head from 'next/head'
import MyNavbar from '../components/navbar'
import { useEffect, useState } from 'react'
import SSRProvider from 'react-bootstrap/SSRProvider';



function MyApp({ Component, pageProps }) {
  const [userData, setUserData] = useState({})

  return <SSRProvider><div className='body'>
    <Head>
      <title>baru tec</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/baru.svg" />
    </Head>

    <MyNavbar userData={userData} {...pageProps} />
    <Component userData={userData} setUserData={setUserData} {...pageProps} />

    <footer id="footer" className="w-100 bg-dark d-flex justify-content-center px-2">
      <div className="d-flex flex-row text-primary">
        <p className='p-2 px-0 m-0 align-middle'>Powered by</p>
        <a href="https://barusystems.com/" target="_blank" rel="noopener noreferrer" className="nav-link px-2" >{' '}<Image src="/baru.svg" alt="baru systems Logo" width={16} height={20} /> </a>
      </div>
    </footer>
  </div></SSRProvider>

}
export default MyApp
