// import 'bootstrap/dist/css/bootstrap.min.css'
import '../styles/globals.css'
import '../styles/scss/global.scss'
import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'

import SSRProvider from 'react-bootstrap/SSRProvider';
import { Navbar, Container, Offcanvas, Nav, NavDropdown, Form, FormControl, Button, Badge } from 'react-bootstrap'
import { useRouter } from 'next/router'
import { useState } from 'react'

function MyApp({ Component, pageProps }) {
  const router = useRouter()
  const [user, setUser] = useState({})

  return <div className='body'>
    <Head>
      <title>baru tec</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/baru.svg" />
    </Head>

    <SSRProvider>
      <Navbar id="navbar" collapseOnSelect expand="lg" bg="dark" variant="dark" className="pb-2 pt-3 shadow-sm">
        <Container fluid className="px-5">
          <Link href="/#navbar" passHref><Navbar.Brand className="p-2 px-4  "><div className='d-flex'><Image alt="Baru Logo" height={30} width={24} src="/baru.svg" /><p className="m-0 p-0 px-3">baru tec</p></div></Navbar.Brand></Link>
          {/* <Link href="/#navbar" passHref><Navbar.Brand style={{ position: "fixed", backgroundColor: "rgba(0,0,0,0.4);" }} className="p-2 px-4 pr-0 rounded-pill border border-primary"><div className='d-flex'><Image alt="Baru Logo" height={30} width={24} src="/baru.svg" /><p className="m-0 p-0 px-3">baru tec</p></div></Navbar.Brand></Link> */}
          <Navbar.Toggle aria-controls="responsive-navbar-nav" />
          <Navbar.Collapse id="responsive-navbar-nav">
            <Nav className="me-auto">
              <Link href="/" passHref><Nav.Link active={router.pathname == "/"}>Startseite</Nav.Link></Link>
              <Nav.Link disabled={Object.getOwnPropertyNames(user).length === 0}>Meine Daten</Nav.Link>
              <Nav.Link disabled={Object.getOwnPropertyNames(user).length === 0}>Meine Einsendungen</Nav.Link>
              <NavDropdown disabled={Object.getOwnPropertyNames(user).length === 0} className="text-primary" title="Nachrichten" id="collasible-nav-dropdown">
                <NavDropdown.Item>Kontakt aufnehmen</NavDropdown.Item>
                <NavDropdown.Divider />
                <NavDropdown.Item>Neuer Status für Antrag 123...</NavDropdown.Item>
                <NavDropdown.Item>Neuer Status für Antrag 321...</NavDropdown.Item>
              </NavDropdown>
            </Nav>
            <Nav>
              {Object.getOwnPropertyNames(user).length === 0 ? (<Link href="/access" passHref><Nav.Link active={router.pathname == "/access"}>Anmelden</Nav.Link></Link>)
                : (<Link href="/logout" passHref><Nav.Link active={router.pathname == "/logout"}>{user.name} abmelden</Nav.Link></Link>)}
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
      <Component {...pageProps} user={user} setUser={setUser} />
    </SSRProvider>

    <footer id="footer" className="w-100 bg-dark d-flex justify-content-center px-2">
      <div className="d-flex flex-row text-primary">
        <p className='p-2 px-0 m-0 align-middle'>Powered by</p>
        <a href="https://barusystems.com/" target="_blank" rel="noopener noreferrer" className="nav-link px-2" >{' '}<Image src="/baru.svg" alt="baru systems Logo" width={16} height={20} /> </a>
      </div>
    </footer>
  </div>

}

export default MyApp
