name: Deployment Workflow
on:
 push:
  branches: [ main ]

jobs:
 job_one:
  name: Deploy
  runs-on: ubuntu-latest
  steps:
  - name: deploy to server
    uses: appleboy/ssh-action@master
    with:
     host: netz.barutec.com 
     username: root
     key: ${{ secrets.id_rsa_barutec }}
     port: 22
     script: |
      cd nextjs-sao
      git stash
      git clean -f
      git pull
      npm -v
      node -v
      npm i
      npm run build
      pm2 reload nextjs-sao || pm2 start npm --name nextjs-sao -- run start
