name: Deployment Workflow
on:
 push:
  branches: [ main ]

jobs:
 job_one:
  name: Deploy
  runs-on: ubuntu-latest
  steps:
  - name: testing server ssh connection
    uses: appleboy/ssh-action@master
    with:
     host: ssh.barutec.com 
     username: root
     key: ${{ secrets.id_rsa_barutec }}
     port: 22
     script: |
      cd nextjs-sao
      git pull
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm install 14
      npm -v
      pm2 list
